language: c

env:
  global:
    - LUAROCKS=2.2.0beta1
  matrix:
    - LUA=lua5.1 ZMQ_VER=zeromq3
    - LUA=lua5.2 ZMQ_VER=zeromq3
    - LUA=luajit ZMQ_VER=zeromq3

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_zmq.sh

install:
  - sudo luarocks install lua-llthreads2

  - if [ $LUA = "luajit" ]; then
      sudo luarocks install ljsyscall 0.9;
    fi

  - if [ $LUA = "luajit" ]; then
      sudo luarocks install lzmq-ffi;
    else
      sudo luarocks install lzmq;
    fi

  - sudo luarocks make rockspecs/lzmq-beacon-scm-0.rockspec

script:
  - cd test
  - lua test_beacon.lua


notifications:
  email:
    on_success: change
    on_failure: always
